eureka:
  client:
    service-url:
      defaultZone: http://www.mll.com:8761/eureka/
spring:
  application:
    name: miaosha
  rabbitmq:
    username: guest
    password: guest
    connection-timeout: 6000
    addresses: 192.168.1.159:5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

    freemarker:
      template-loader-path: classpath:/templates/
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      allow-request-override: false
      suffix: .ftl

  druid:
    url: jdbc:mysql://192.168.1.111/mll?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #最大链接数
    maxActive: 30
    #最小链接数
    minIdle: 5
    #获得链接的最大等待时间
    maxWait: 10000

  redis:
    database: 0
    host: 192.168.1.159
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 6000

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
server:
  port: 9001

ribbon:
  eureka:
    enabled: true






