
eureka:
  client:
    service-url:
      defaultZone: http://www.mll.com:8761/eureka/

spring:
  application:
    name: product
  rabbitmq:
    username: guest
    password: guest
    connection-timeout: 6000
    addresses: 192.168.1.159:5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        #手动确认
        acknowledge-mode: manual
        #在消费端创建多少个线程 对队列中的消息进行消费
        #如果消息很多 就可以启动多线程消费  但是如果要保证消息的顺序最好使用一个
        concurrency: 1
        #表示最多可以创建多少个线程  因为是连接池创建的
        max-concurrency: 1
        #就是qos  表示一次在消息队列中取多少消息  限流的目的
        prefetch: 1
  druid:
    url: jdbc:mysql://192.168.1.111/mll?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    maxActive: 30
    minIdle: 5
    maxWait: 10000
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
server:
  port: 9002

ribbon:
  eureka:
    enabled: true



