spring:
  datasource:
    url: jdbc:mysql://192.168.1.111/mll?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  security:
    user:
      password: xmcc
      name: xmcc

xmcc:
  security:
    browser:
      loginPage: /demo_login.html
      loginType: JSON